# fp=open("19aug.txt","a")
# fp.write("This is a new line added to the file.\n")
# # fp.close()
# fp=open("19aug.txt","r")
# content=fp.read()
# print(content)
# fp.close()
# fp=open("19aug.txt","a")
# fp.write("Name:abhinav\n")
# fp.write("course:CSE\n")
# fp.close()
# fp=open("19aug2.txt","a")
# fp.write("Name:abhinav\n")
# fp.write("course:CSE\n")
# fp.close()
# fp=open("","r")
# content=fp.read(10)
# print(content)
# fp.close()
# print("Learning to move the fi le object")
# fileobject=open("testfi le.txt","r+")
# str=fileobject.read()
# print(str)
# print("Initially, the position of the fi le object is: ",fileobject.
# tell())
# fileobject.seek(0)
# print("Now the fi le object is at the beginning of the fi le:",fileobject.tell())
# fileobject.seek(10)
# print("We are moving to 10th byte position from the beginning offi le")
# print("The position of the fi le object is at", fileobject.tell())
# str=fileobject.read()
# print(str)
# fp=open("19aug.txt","r")
# content=fp.read()
# print(content)
# fp.close()
f=open("filename", "r", buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)
print(type(f))